package com.cjeg.web.admin.mapper;

import java.util.List;

import com.cjeg.web.admin.model.Goods;

public interface GoodsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods_t
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods_t
	 * @mbg.generated
	 */
	int insert(Goods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods_t
	 * @mbg.generated
	 */
	int insertSelective(Goods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods_t
	 * @mbg.generated
	 */
	Goods selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods_t
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Goods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods_t
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Goods record);

	List<Goods> selectSelective(Goods record);
}