package com.cjeg.web.admin.mapper;

import java.util.List;

import com.cjeg.web.admin.model.Member;

public interface MemberMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_t
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_t
	 * @mbg.generated
	 */
	int insert(Member record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_t
	 * @mbg.generated
	 */
	int insertSelective(Member record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_t
	 * @mbg.generated
	 */
	Member selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_t
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Member record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member_t
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Member record);

	List<Member> selectSelective(Member record);
}