package com.cjeg.web.admin.mapper;

import java.util.List;

import com.cjeg.web.admin.model.Person;

public interface PersonMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person_t
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person_t
	 * @mbg.generated
	 */
	int insert(Person record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person_t
	 * @mbg.generated
	 */
	int insertSelective(Person record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person_t
	 * @mbg.generated
	 */
	Person selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person_t
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Person record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person_t
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Person record);

	List<Person> selectSelective(Person record);
}