package com.cjeg.web.admin.mapper;

import java.util.List;

import com.cjeg.web.admin.model.Type;

public interface TypeMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table type_t
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table type_t
	 * @mbg.generated
	 */
	int insert(Type record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table type_t
	 * @mbg.generated
	 */
	int insertSelective(Type record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table type_t
	 * @mbg.generated
	 */
	Type selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table type_t
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Type record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table type_t
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Type record);

	List<Type> selectSelective(Type record);
}