package com.cjeg.web.admin.model;

import java.util.Date;

public class Goods {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods_t.id
	 * @mbg.generated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods_t.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods_t.number
	 * @mbg.generated
	 */
	private Integer number;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods_t.status
	 * @mbg.generated
	 */
	private Boolean status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods_t.type_id
	 * @mbg.generated
	 */
	private String typeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods_t.discripts
	 * @mbg.generated
	 */
	private String discripts;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods_t.create_time
	 * @mbg.generated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column goods_t.update_time
	 * @mbg.generated
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods_t.id
	 * @return  the value of goods_t.id
	 * @mbg.generated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods_t.id
	 * @param id  the value for goods_t.id
	 * @mbg.generated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods_t.name
	 * @return  the value of goods_t.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods_t.name
	 * @param name  the value for goods_t.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods_t.number
	 * @return  the value of goods_t.number
	 * @mbg.generated
	 */
	public Integer getNumber() {
		return number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods_t.number
	 * @param number  the value for goods_t.number
	 * @mbg.generated
	 */
	public void setNumber(Integer number) {
		this.number = number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods_t.status
	 * @return  the value of goods_t.status
	 * @mbg.generated
	 */
	public Boolean getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods_t.status
	 * @param status  the value for goods_t.status
	 * @mbg.generated
	 */
	public void setStatus(Boolean status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods_t.type_id
	 * @return  the value of goods_t.type_id
	 * @mbg.generated
	 */
	public String getTypeId() {
		return typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods_t.type_id
	 * @param typeId  the value for goods_t.type_id
	 * @mbg.generated
	 */
	public void setTypeId(String typeId) {
		this.typeId = typeId == null ? null : typeId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods_t.discripts
	 * @return  the value of goods_t.discripts
	 * @mbg.generated
	 */
	public String getDiscripts() {
		return discripts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods_t.discripts
	 * @param discripts  the value for goods_t.discripts
	 * @mbg.generated
	 */
	public void setDiscripts(String discripts) {
		this.discripts = discripts == null ? null : discripts.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods_t.create_time
	 * @return  the value of goods_t.create_time
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods_t.create_time
	 * @param createTime  the value for goods_t.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column goods_t.update_time
	 * @return  the value of goods_t.update_time
	 * @mbg.generated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column goods_t.update_time
	 * @param updateTime  the value for goods_t.update_time
	 * @mbg.generated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	private Type type;

	public Type getType() {
		return type;
	}

	public void setType(Type type) {
		this.type = type;
	}
	
	
}