package com.cjeg.web.admin.model;

import java.util.Date;

public class Member {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_t.id
	 * @mbg.generated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_t.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_t.sex
	 * @mbg.generated
	 */
	private Boolean sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_t.in_date
	 * @mbg.generated
	 */
	private Date inDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_t.rname
	 * @mbg.generated
	 */
	private String rname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_t.create_time
	 * @mbg.generated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_t.update_time
	 * @mbg.generated
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_t.type
	 * @mbg.generated
	 */
	private Byte type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member_t.password
	 * @mbg.generated
	 */
	private String password;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_t.id
	 * @return  the value of member_t.id
	 * @mbg.generated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_t.id
	 * @param id  the value for member_t.id
	 * @mbg.generated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_t.name
	 * @return  the value of member_t.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_t.name
	 * @param name  the value for member_t.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_t.sex
	 * @return  the value of member_t.sex
	 * @mbg.generated
	 */
	public Boolean getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_t.sex
	 * @param sex  the value for member_t.sex
	 * @mbg.generated
	 */
	public void setSex(Boolean sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_t.in_date
	 * @return  the value of member_t.in_date
	 * @mbg.generated
	 */
	public Date getInDate() {
		return inDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_t.in_date
	 * @param inDate  the value for member_t.in_date
	 * @mbg.generated
	 */
	public void setInDate(Date inDate) {
		this.inDate = inDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_t.rname
	 * @return  the value of member_t.rname
	 * @mbg.generated
	 */
	public String getRname() {
		return rname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_t.rname
	 * @param rname  the value for member_t.rname
	 * @mbg.generated
	 */
	public void setRname(String rname) {
		this.rname = rname == null ? null : rname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_t.create_time
	 * @return  the value of member_t.create_time
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_t.create_time
	 * @param createTime  the value for member_t.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_t.update_time
	 * @return  the value of member_t.update_time
	 * @mbg.generated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_t.update_time
	 * @param updateTime  the value for member_t.update_time
	 * @mbg.generated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_t.type
	 * @return  the value of member_t.type
	 * @mbg.generated
	 */
	public Byte getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_t.type
	 * @param type  the value for member_t.type
	 * @mbg.generated
	 */
	public void setType(Byte type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member_t.password
	 * @return  the value of member_t.password
	 * @mbg.generated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member_t.password
	 * @param password  the value for member_t.password
	 * @mbg.generated
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	@Override
	public String toString() {
		return "Member [id=" + id + ", name=" + name + ", sex=" + sex
				+ ", inDate=" + inDate + ", rname=" + rname + ", createTime="
				+ createTime + ", updateTime=" + updateTime + ", type=" + type
				+ ", password=" + password + "]";
	}
	
	
}