package com.cjeg.web.admin.model;

import java.util.Date;

public class Person {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column person_t.id
	 * @mbg.generated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column person_t.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column person_t.phone
	 * @mbg.generated
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column person_t.addr
	 * @mbg.generated
	 */
	private String addr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column person_t.sex
	 * @mbg.generated
	 */
	private Boolean sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column person_t.create_time
	 * @mbg.generated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column person_t.update_time
	 * @mbg.generated
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column person_t.id
	 * @return  the value of person_t.id
	 * @mbg.generated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column person_t.id
	 * @param id  the value for person_t.id
	 * @mbg.generated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column person_t.name
	 * @return  the value of person_t.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column person_t.name
	 * @param name  the value for person_t.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column person_t.phone
	 * @return  the value of person_t.phone
	 * @mbg.generated
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column person_t.phone
	 * @param phone  the value for person_t.phone
	 * @mbg.generated
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column person_t.addr
	 * @return  the value of person_t.addr
	 * @mbg.generated
	 */
	public String getAddr() {
		return addr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column person_t.addr
	 * @param addr  the value for person_t.addr
	 * @mbg.generated
	 */
	public void setAddr(String addr) {
		this.addr = addr == null ? null : addr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column person_t.sex
	 * @return  the value of person_t.sex
	 * @mbg.generated
	 */
	public Boolean getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column person_t.sex
	 * @param sex  the value for person_t.sex
	 * @mbg.generated
	 */
	public void setSex(Boolean sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column person_t.create_time
	 * @return  the value of person_t.create_time
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column person_t.create_time
	 * @param createTime  the value for person_t.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column person_t.update_time
	 * @return  the value of person_t.update_time
	 * @mbg.generated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column person_t.update_time
	 * @param updateTime  the value for person_t.update_time
	 * @mbg.generated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}