package com.cjeg.web.admin.model;

import java.util.Date;

public class TransRecode {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trans_recode.id
	 * @mbg.generated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trans_recode.goods_id
	 * @mbg.generated
	 */
	private String goodsId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trans_recode.person_id
	 * @mbg.generated
	 */
	private String personId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trans_recode.member_id
	 * @mbg.generated
	 */
	private String memberId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trans_recode.type
	 * @mbg.generated
	 */
	private Byte type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trans_recode.number
	 * @mbg.generated
	 */
	private Integer number;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trans_recode.price
	 * @mbg.generated
	 */
	private Float price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trans_recode.amount
	 * @mbg.generated
	 */
	private Float amount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trans_recode.create_time
	 * @mbg.generated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trans_recode.update_time
	 * @mbg.generated
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trans_recode.descripts
	 * @mbg.generated
	 */
	private String descripts;
	
	private Goods goods;
	
	private Member member;
	
	private Person person;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trans_recode.id
	 * @return  the value of trans_recode.id
	 * @mbg.generated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trans_recode.id
	 * @param id  the value for trans_recode.id
	 * @mbg.generated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trans_recode.goods_id
	 * @return  the value of trans_recode.goods_id
	 * @mbg.generated
	 */
	public String getGoodsId() {
		return goodsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trans_recode.goods_id
	 * @param goodsId  the value for trans_recode.goods_id
	 * @mbg.generated
	 */
	public void setGoodsId(String goodsId) {
		this.goodsId = goodsId == null ? null : goodsId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trans_recode.person_id
	 * @return  the value of trans_recode.person_id
	 * @mbg.generated
	 */
	public String getPersonId() {
		return personId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trans_recode.person_id
	 * @param personId  the value for trans_recode.person_id
	 * @mbg.generated
	 */
	public void setPersonId(String personId) {
		this.personId = personId == null ? null : personId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trans_recode.member_id
	 * @return  the value of trans_recode.member_id
	 * @mbg.generated
	 */
	public String getMemberId() {
		return memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trans_recode.member_id
	 * @param memberId  the value for trans_recode.member_id
	 * @mbg.generated
	 */
	public void setMemberId(String memberId) {
		this.memberId = memberId == null ? null : memberId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trans_recode.type
	 * @return  the value of trans_recode.type
	 * @mbg.generated
	 */
	public Byte getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trans_recode.type
	 * @param type  the value for trans_recode.type
	 * @mbg.generated
	 */
	public void setType(Byte type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trans_recode.number
	 * @return  the value of trans_recode.number
	 * @mbg.generated
	 */
	public Integer getNumber() {
		return number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trans_recode.number
	 * @param number  the value for trans_recode.number
	 * @mbg.generated
	 */
	public void setNumber(Integer number) {
		this.number = number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trans_recode.price
	 * @return  the value of trans_recode.price
	 * @mbg.generated
	 */
	public Float getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trans_recode.price
	 * @param price  the value for trans_recode.price
	 * @mbg.generated
	 */
	public void setPrice(Float price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trans_recode.amount
	 * @return  the value of trans_recode.amount
	 * @mbg.generated
	 */
	public Float getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trans_recode.amount
	 * @param amount  the value for trans_recode.amount
	 * @mbg.generated
	 */
	public void setAmount(Float amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trans_recode.create_time
	 * @return  the value of trans_recode.create_time
	 * @mbg.generated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trans_recode.create_time
	 * @param createTime  the value for trans_recode.create_time
	 * @mbg.generated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trans_recode.update_time
	 * @return  the value of trans_recode.update_time
	 * @mbg.generated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trans_recode.update_time
	 * @param updateTime  the value for trans_recode.update_time
	 * @mbg.generated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trans_recode.descripts
	 * @return  the value of trans_recode.descripts
	 * @mbg.generated
	 */
	public String getDescripts() {
		return descripts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trans_recode.descripts
	 * @param descripts  the value for trans_recode.descripts
	 * @mbg.generated
	 */
	public void setDescripts(String descripts) {
		this.descripts = descripts == null ? null : descripts.trim();
	}

	public Goods getGoods() {
		return goods;
	}

	public void setGoods(Goods goods) {
		this.goods = goods;
	}

	public Member getMember() {
		return member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public Person getPerson() {
		return person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@Override
	public String toString() {
		return "TransRecode [id=" + id + ", goodsId=" + goodsId + ", personId="
				+ personId + ", memberId=" + memberId + ", type=" + type
				+ ", number=" + number + ", price=" + price + ", amount="
				+ amount + ", createTime=" + createTime + ", updateTime="
				+ updateTime + ", descripts=" + descripts + ", goods=" + goods
				+ ", member=" + member + ", person=" + person + "]";
	}
	
	
}